language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jgonyon/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jgonyon/docker-react npm run test 